apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base.yaml
patches:
  - target:
      kind: Kustomization
      name: vllm
    patch: |
      - op: replace
        path: /spec/suspend
        value: false
