apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-example-app-pdb
  namespace: workload
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
